# Generated by Django 4.2.1 on 2023-06-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupoZero', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='foto',
            field=models.ImageField(null=True, upload_to='artista'),
        ),
    ]
