# Generated by Django 4.2.1 on 2023-06-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupoZero', '0004_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='precio',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
