# Generated by Django 4.2.1 on 2023-07-03 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupoZero', '0006_artista_descripcion_artista_usuario_obra_estado_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='tipo',
        ),
        migrations.AddField(
            model_name='obra',
            name='artista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGrupoZero.artista'),
        ),
    ]
