# Generated by Django 4.2.1 on 2023-07-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupoZero', '0007_remove_obra_tipo_obra_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='precio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
