# Generated by Django 4.2.1 on 2023-07-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupoZero', '0010_alter_artista_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='rut',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
