# Generated by Django 4.2.1 on 2023-07-13 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupoZero', '0011_alter_artista_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGrupoZero.tipo'),
        ),
    ]
