# Generated by Django 4.2.1 on 2023-07-13 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupoZero', '0014_obra_usuario_alter_obra_artista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='artista',
        ),
    ]
