# Generated by Django 4.2.1 on 2023-07-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupoZero', '0015_remove_obra_artista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('descripcion', models.CharField(max_length=400, null=True)),
                ('direccion', models.CharField(max_length=100)),
                ('foto', models.ImageField(null=True, upload_to='postulacion')),
                ('cv', models.FileField(null=True, upload_to='postulacion')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGrupoZero.tipo')),
            ],
        ),
    ]
