# Generated by Django 4.2.1 on 2023-07-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGrupoZero', '0016_postular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postular',
            name='cv',
            field=models.FileField(default=' ', null=True, upload_to='postulacion'),
        ),
        migrations.AlterField(
            model_name='postular',
            name='foto',
            field=models.ImageField(default=' ', null=True, upload_to='postulacion'),
        ),
    ]
